#!/bin/sh

set(haskell_env
  ${CMAKE_COMMAND} -E env
  "PATH=${CABAL_PATH_ENTRY}${THIRD_PARTY_DIR}/ghc/bin/:${PATH}"
  "LIBRARY_PATH=${GMP_LIBRARIES_DIR}:${ZLIB_LIBRARIES_DIR}"
  "LD_LIBRARY_PATH=${GMP_LIBRARIES_DIR}:${ZLIB_LIBRARIES_DIR}"
  "HOME=${CMAKE_CURRENT_BINARY_DIR}/cabal-home"
)
