#!/bin/bash

# exit if any command fails
set -e

# do awk before
if [ $# -eq 3 ]; then
	# need to execute awk explicitely without process substition <( ) to be able to check the exit code
	output1=`awk "$3" $1`
	output2=`awk "$3" $2`

	# check if either output is empty, caused e.g. by a malformed regex or awk action
	if [ -z "$output1" ] || [ -z "$output2" ] ; then
		echo "Output check failed, at least one awk output was empty! Perhaps your regular expression did not match anything?"
		exit 1
	fi

	# execute awk with process substitution and feed output to diff
	diff <(awk "$3" $1) <(awk "$3" $2)
else
	diff $1 $2
fi
