#!/bin/bash

set -e

export INSTALLER_DIR="$(dirname "$(readlink -f "$0")")"

source "$INSTALLER_DIR/config.sh"
source "$INSTALLER_DIR/internal/functions.sh"
source "$INSTALLER_DIR/internal/install_steps.sh"

if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
	echo "usage: $0 <package_name>..."
	exit 1
fi

for pkg in "$@"; do
	assert_pkg_exists $pkg

	if is_pkg_installed $pkg; then
		echo "$(get_property $pkg PACKAGE) already installed"
		continue
	fi

	install_pkg $pkg
done
