#!/usr/bin/env ruby

require 'date'

USAGE = <<EOS
Usage: #{$PROGRAM_NAME} <license-file> <code-file> [output-file]

Replaces existing license header, prepends if no license header present, no
changes if license up to date. If no output file is provided, the code file
will be overwritten.
EOS

# The license recognition:
# A comment at the start of the file, which contains "COPYRIGHT"
LICENSE_REGEXP = /\A\s*(\/\*|\{-).*?COPYRIGHT.*?(\*\/|-\})/mi

if(ARGV.length < 2 || ARGV.length > 3)
	puts(USAGE)
	exit(false)
end

license = IO.read(ARGV[0])

# update license year to current
license.sub!(/20XX/, Date.today.year.to_s)

file = IO.read(ARGV[1])

match = LICENSE_REGEXP.match(file)

# check if any existing license
if(match)
	# if up-to-date, exit
	exit(true) if(match[0].strip == license.strip)
	# else, delete existing license
	file.sub!(match[0], "");
end

# prepend new license
output = license + "\n" + file.lstrip

# write ouptput to code file, or output file if specified 
outfn = ARGV[ARGV.length - 1]

File.open(outfn, "wb+") do |f|
	f.print(output)
end

exit(true)
