#!/bin/sh
#
# In this pre-commit hook we are verifying that all files have
# the proper license header before commiting them.
#


for f in `git diff --cached --name-only | grep -i "code/.*\.\(h\|hpp\|hxx\|c\|cpp\|cxx\|cl\|cc\|inc\|def\|in\|hs\|chs\)$"` ; do

	# files which have execute permissions (as happens when edited via a Samba share) should have them removed
	if [ -x "$f" ]; then
		chmod a-x $f
		git add $f
	fi

	# check whether disk version is the same as the version to be commited
	git diff --quiet $f
	upToDate=$?

	# adding license to file (if not present)
	if [ ${f: -3} == ".hs" ] || [ ${f: -4} == ".chs" ]; then
		header="./scripts/license/license_header_haskell.txt"
	else
		header="./scripts/license/license_header.txt"
	fi
	ruby ./scripts/license/licensor.rb $header $f
	licened=$?

	# check whether modification can / needs to be commited
	if [ $licened -eq 0 ] ; then
		if [ $upToDate -eq 0 ] ; then
			# newly licented file can be commited
			git add $f
		else
			# license had to be added, but there are uncommited changes
			echo "ERROR: file $f required licening but contained uncommited changes!\n"
			exit 1		# abort commit
		fi
	fi

done
