#!/bin/bash

set -ex

cd "$BUILD_DIR"

cmake "$WORKSPACE/code" \
	-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DCMAKE_CXX_FLAGS="-Werror" \
	-DBUILD_DOCS=ON \
	-DBUILD_COVERAGE=ON

make -j "$NPROC"

driver/integration_tests --preprocess
