#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR/driver"

# Arguments used to run this script are forwarded to the runner.
./integration_tests -w "$NPROC" "$@"

# Cleanup.
./integration_tests --postprocessing
