// compute the set of polymorth types
.decl isPolymorph ( id : node )

isPolymorph(X) :- TypeVariable(X,_).

isPolymorph(X) :- TupleType(X), NodeList(X,_,Y), isPolymorph(Y).

isPolymorph(X) :- GenericType(X,_,P,_), NodeList(P,_,Y), isPolymorph(Y).
isPolymorph(X) :- GenericType(X,_,_,P), NodeList(P,_,Y), isPolymorph(Y).

// define the result
.decl result ( x : number ) output
result(X) :- isPolymorph(X).


