#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

cmake "$WORKSPACE/code" \
	-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DCMAKE_CXX_FLAGS="-Werror" \
	-DANALYSIS_DATALOG=ON -DSOUFFLE_ROOT="$BUILD_DIR/third_party/souffle" \
	-DANALYSIS_HASKELL=ON -DCABAL_ROOT="$BUILD_DIR/third_party/cabal"

make -j "$NPROC"

driver/integration_tests --preprocess
