#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

cmake "$WORKSPACE/code" \
	-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DCMAKE_CXX_FLAGS="-Werror" \
	-DANALYSIS_DATALOG=ON -DSOUFFLE_ROOT="$WORKSPACE/third_party/souffle" \
	-DANALYSIS_HASKELL=ON -DSTACK_ROOT="$WORKSPACE/third_party/stack"

make -j "$NPROC"

driver/integration_tests --preprocess

if [[ -n "${STACK_ROOT+x}" && "$(hostname)" == "hudson.dps.uibk.ac.at" ]]; then
	# Grant everybody write permissions to stack-root
	chmod -R a+w "$STACK_ROOT"
fi
