#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

# Use LD_LIBRARY_PATH folders for rpath. This is required as permission setting
# (see below) clears the LD_LIBRARY_PATH for security reasons.
rpath_flags=""
for r in ${LD_LIBRARY_PATH//:/ }; do
	rpath_flags="$rpath_flags -Wl,-rpath,$r"
done

cmake "$WORKSPACE/code" \
	-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DCMAKE_CXX_FLAGS="-Werror" \
	-DCMAKE_CXX_LINK_FLAGS="$rpath_flags" \
	-DUSE_OPENCL=ON -DOPENCL_ROOT="$OPENCL_ROOT" \
	-DUSE_ENERGY=ON \
	-DUSE_VALGRIND=ON

make -j "$NPROC"

driver/integration_tests --preprocess

# Setup restrictions and permissions for CI server.
if [[ -n "$RUNNING_ON_CI_SERVER" ]]; then
	# Set permissions for RAPL tests.
	sudo /sbin/setcap cap_sys_rawio=ep runtime/ut_runtime_energy_test
	sudo /sbin/setcap cap_sys_rawio=ep runtime/ut_runtime_instrumentation_regions_test
	/sbin/getcap runtime/ut_runtime_energy_test
	/sbin/getcap runtime/ut_runtime_instrumentation_regions_test
fi
