#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

# Remove Haskell Stack's Working Directory to simulate a clean installation.
rm -rf "$WORKSPACE/code/analysis/src/cba/haskell/insieme-hat/.stack-work"
