macro(msvc_file_completion target_name input_dir)
	if (MSVC)
		foreach(ext in list ${ARGN})
			LIST(APPEND _globs "${input_dir}/*.${ext}")
		endforeach(ext)
		file(GLOB_RECURSE ${target_name}_files ${_globs})
		add_custom_target(${target_name} SOURCES ${${target_name}_files})
	endif()
endmacro()
